services:
  - type: web
    name: OptionBuyerBot
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
